In [1]:
from replan2eplus.paths import TWO_ROOM_RESULTS
from replan2eplus.ezcase.read import ExistCase
from replan2eplus.examples.defaults import PATH_TO_IDD
from replan2eplus.results.collections import (
    DFC,
    QOIResult,
    sqlcollections_to_qoi_result,
)
from replan2eplus.results.sql import create_result_for_qoi, get_sql_results
from replan2eplus.idfobjects.variables import OutputVariables
from rich import print as rprint
import pytest
import numpy as np
import xarray as xr

In [2]:
def get_qoi(qoi: OutputVariables):
    sql = get_sql_results(TWO_ROOM_RESULTS)
    return create_result_for_qoi(sql, qoi)

def plot_values():
    case = ExistCase(PATH_TO_IDD, TWO_ROOM_RESULTS / "out.idf")
    pressure = get_qoi("AFN Node Total Pressure")
    noon_pressure = pressure.select_time(12)
    return noon_pressure, pressure

In [3]:
noon_pressure, pressure = plot_values()
noon_pressure

<xarray.DataArray (space_names: 5)> Size: 40B
array([-0.13187061, -0.22147448, -0.59995232,  0.8975094 , -0.38854307])
Coordinates:
    datetimes    datetime64[ns] 8B 2017-07-01T12:00:00
  * space_names  (space_names) <U22 440B 'BLOCK `ROOM1` STOREY 0' ... 'ExtNod...

In [4]:
abs(noon_pressure)

<xarray.DataArray (space_names: 5)> Size: 40B
array([0.13187061, 0.22147448, 0.59995232, 0.8975094 , 0.38854307])
Coordinates:
    datetimes    datetime64[ns] 8B 2017-07-01T12:00:00
  * space_names  (space_names) <U22 440B 'BLOCK `ROOM1` STOREY 0' ... 'ExtNod...

In [8]:
noon_pressure["space_names"]

<xarray.DataArray 'space_names' (space_names: 3)> Size: 264B
array(['BLOCK `ROOM1` STOREY 0', 'ExtNode   1', 'ExtNode   2'], dtype='<U22')
Coordinates:
  * space_names  (space_names) <U22 264B 'BLOCK `ROOM1` STOREY 0' ... 'ExtNod...

In [43]:
arr = noon_pressure
lst = ['BLOCK `ROOM1` STOREY 0', 'ExtNode   2']
arr.squeeze().sel(space_names=lst).values

array([0.16881821, 0.8975094 ])

In [42]:
arr.values

array([[ 0.16881821, -0.59995232,  0.8975094 ]])

In [15]:
full_arr = pressure.data_arr
full_arr

<xarray.DataArray (datetimes: 96, space_names: 3)> Size: 2kB
array([[-1.45937177e-01,  9.61248433e-02,  4.14867388e-02],
       [-1.48793921e-01,  9.89173214e-02,  2.50727253e-02],
       [-1.77845460e-01,  9.28251146e-02,  4.76729605e-03],
       [-2.06708960e-01,  8.63292010e-02, -1.14888292e-02],
       [-2.07806501e-01,  7.93164635e-02, -1.05555628e-02],
       [-2.12894344e-01,  7.25981459e-02, -9.66147830e-03],
       [-2.16819693e-01,  6.61745994e-02, -8.80662237e-03],
       [-2.19500126e-01,  6.00461754e-02, -7.99104182e-03],
       [-2.37328945e-01,  3.52299105e-02,  2.35589705e-02],
       [-2.63696131e-01,  1.00419601e-02,  3.96177032e-02],
       [-2.45440839e-01, -1.79604696e-02,  3.92608313e-02],
       [-2.39557258e-01, -2.99420308e-02,  3.20410661e-02],
       [-2.37578607e-01, -2.58259145e-02,  2.76363964e-02],
       [-2.42082222e-01, -2.20127964e-02,  2.35559661e-02],
       [-2.48007682e-01, -1.85029814e-02,  1.98001015e-02],
       [-2.51260982e-01, -1.52967742e-02,  1.63691286e-02],
       [-2.53259723e-01, -1.10558711e-02,  1.18309242e-02],
       [-2.55793641e-01, -7.50078546e-03,  8.02661529e-03],
       [-2.56879967e-01, -4.63224879e-03,  4.95698473e-03],
       [-2.56512879e-01, -2.45099597e-03,  2.62281888e-03],
...
       [ 1.58901091e-01,  2.48106174e-01,  3.02788813e-01],
       [ 1.00635415e-01,  2.52171574e-01,  2.52171574e-01],
       [ 7.23070203e-02,  2.52731145e-01,  2.07088752e-01],
       [ 8.26701337e-02,  2.50089063e-01,  1.67239734e-01],
       [ 5.88654478e-02,  2.40494262e-01,  1.60823492e-01],
       [ 4.00543829e-02,  2.31077301e-01,  1.54526175e-01],
       [ 2.31280686e-02,  2.21838548e-01,  1.48348030e-01],
       [ 7.23970001e-03,  2.12778399e-01,  1.42289321e-01],
       [-1.00797446e-03,  1.99232984e-01,  1.33231221e-01],
       [-1.40228054e-02,  1.86126450e-01,  1.24466611e-01],
       [-2.75234516e-02,  1.73459447e-01,  1.15995924e-01],
       [-4.03780210e-02,  1.61232628e-01,  1.07819597e-01],
       [-4.81458307e-02,  1.53336767e-01,  1.02539471e-01],
       [-5.57029323e-02,  1.45636075e-01,  9.73898584e-02],
       [-6.31871038e-02,  1.38130774e-01,  9.23709084e-02],
       [-7.05933995e-02,  1.30821089e-01,  8.74827706e-02],
       [-8.15411866e-02,  1.20204000e-01,  8.03829033e-02],
       [-9.32649543e-02,  1.10031648e-01,  7.35804413e-02],
       [-1.05472117e-01,  1.00304608e-01,  6.70757680e-02],
       [-1.16884681e-01,  9.10234591e-02,  6.08692716e-02]])
Coordinates:
  * datetimes    (datetimes) datetime64[ns] 768B 2017-07-01 ... 2017-07-01T23...
  * space_names  (space_names) <U22 264B 'BLOCK `ROOM1` STOREY 0' ... 'ExtNod...

In [26]:
full_arr.datetimes.dt.time

<xarray.DataArray 'time' (datetimes: 96)> Size: 768B
array([datetime.time(0, 0), datetime.time(0, 15), datetime.time(0, 30),
       datetime.time(0, 45), datetime.time(1, 0), datetime.time(1, 15),
       datetime.time(1, 30), datetime.time(1, 45), datetime.time(2, 0),
       datetime.time(2, 15), datetime.time(2, 30), datetime.time(2, 45),
       datetime.time(3, 0), datetime.time(3, 15), datetime.time(3, 30),
       datetime.time(3, 45), datetime.time(4, 0), datetime.time(4, 15),
       datetime.time(4, 30), datetime.time(4, 45), datetime.time(5, 0),
       datetime.time(5, 15), datetime.time(5, 30), datetime.time(5, 45),
       datetime.time(6, 0), datetime.time(6, 15), datetime.time(6, 30),
       datetime.time(6, 45), datetime.time(7, 0), datetime.time(7, 15),
       datetime.time(7, 30), datetime.time(7, 45), datetime.time(8, 0),
       datetime.time(8, 15), datetime.time(8, 30), datetime.time(8, 45),
       datetime.time(9, 0), datetime.time(9, 15), datetime.time(9, 30),
       datetime.time(9, 45), datetime.time(10, 0), datetime.time(10, 15),
       datetime.time(10, 30), datetime.time(10, 45), datetime.time(11, 0),
       datetime.time(11, 15), datetime.time(11, 30),
       datetime.time(11, 45), datetime.time(12, 0), datetime.time(12, 15),
       datetime.time(12, 30), datetime.time(12, 45), datetime.time(13, 0),
       datetime.time(13, 15), datetime.time(13, 30),
       datetime.time(13, 45), datetime.time(14, 0), datetime.time(14, 15),
       datetime.time(14, 30), datetime.time(14, 45), datetime.time(15, 0),
       datetime.time(15, 15), datetime.time(15, 30),
       datetime.time(15, 45), datetime.time(16, 0), datetime.time(16, 15),
       datetime.time(16, 30), datetime.time(16, 45), datetime.time(17, 0),
       datetime.time(17, 15), datetime.time(17, 30),
       datetime.time(17, 45), datetime.time(18, 0), datetime.time(18, 15),
       datetime.time(18, 30), datetime.time(18, 45), datetime.time(19, 0),
       datetime.time(19, 15), datetime.time(19, 30),
       datetime.time(19, 45), datetime.time(20, 0), datetime.time(20, 15),
       datetime.time(20, 30), datetime.time(20, 45), datetime.time(21, 0),
       datetime.time(21, 15), datetime.time(21, 30),
       datetime.time(21, 45), datetime.time(22, 0), datetime.time(22, 15),
       datetime.time(22, 30), datetime.time(22, 45), datetime.time(23, 0),
       datetime.time(23, 15), datetime.time(23, 30),
       datetime.time(23, 45)], dtype=object)
Coordinates:
  * datetimes  (datetimes) datetime64[ns] 768B 2017-07-01 ... 2017-07-01T23:4...

In [16]:
import datetime

In [22]:
full_arr.sel(datetimes=datetime.time(12,0)).squeeze()

<xarray.DataArray (space_names: 3)> Size: 24B
array([ 0.16881821, -0.59995232,  0.8975094 ])
Coordinates:
    datetimes    datetime64[ns] 8B 2017-07-01T12:00:00
  * space_names  (space_names) <U22 264B 'BLOCK `ROOM1` STOREY 0' ... 'ExtNod...

In [18]:
full_arr.values

array([[-1.45937177e-01,  9.61248433e-02,  4.14867388e-02],
       [-1.48793921e-01,  9.89173214e-02,  2.50727253e-02],
       [-1.77845460e-01,  9.28251146e-02,  4.76729605e-03],
       [-2.06708960e-01,  8.63292010e-02, -1.14888292e-02],
       [-2.07806501e-01,  7.93164635e-02, -1.05555628e-02],
       [-2.12894344e-01,  7.25981459e-02, -9.66147830e-03],
       [-2.16819693e-01,  6.61745994e-02, -8.80662237e-03],
       [-2.19500126e-01,  6.00461754e-02, -7.99104182e-03],
       [-2.37328945e-01,  3.52299105e-02,  2.35589705e-02],
       [-2.63696131e-01,  1.00419601e-02,  3.96177032e-02],
       [-2.45440839e-01, -1.79604696e-02,  3.92608313e-02],
       [-2.39557258e-01, -2.99420308e-02,  3.20410661e-02],
       [-2.37578607e-01, -2.58259145e-02,  2.76363964e-02],
       [-2.42082222e-01, -2.20127964e-02,  2.35559661e-02],
       [-2.48007682e-01, -1.85029814e-02,  1.98001015e-02],
       [-2.51260982e-01, -1.52967742e-02,  1.63691286e-02],
       [-2.53259723e-01, -1.10558711e-02

In [4]:
noon_pressure

array([ 0.16881821, -0.59995232,  0.8975094 ])

In [29]:
noon_pressure.sizes["space_names"]

3

In [33]:
vals = noon_pressure.squeeze().values
vals

array([ 0.16881821, -0.59995232,  0.8975094 ])

In [34]:
type(vals)

numpy.ndarray

In [36]:
min(vals) * 1.2

np.float64(-0.7199427828086187)